#!/bin/bash
# Deploys all 5 lingualayer contracts to a Soroban network in dependency
# order, initializes each with the correct cross-contract addresses, and
# writes the resulting deployed IDs to deployment/testnet.json.
#
# Usage:
#   ./deployment/deploy.sh [network] [admin-identity]
#
#   network         stellar CLI network alias (default: testnet)
#   admin-identity  stellar CLI identity to deploy/initialize as (default: admin)
#
# Requires: cargo, the wasm32-unknown-unknown target, and the `stellar` CLI
# with `admin-identity` already funded and configured for `network`.
set -euo pipefail

NETWORK="${1:-testnet}"
ADMIN="${2:-admin}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
WASM_DIR="$ROOT_DIR/target/wasm32-unknown-unknown/release"
OUT_FILE="$SCRIPT_DIR/testnet.json"

echo "==> Building all contracts (release wasm)"
cargo build --manifest-path "$ROOT_DIR/Cargo.toml" \
    --target wasm32-unknown-unknown --release --workspace

deploy() {
    local wasm_name="$1"
    stellar contract deploy \
        --wasm "$WASM_DIR/${wasm_name}.wasm" \
        --source "$ADMIN" \
        --network "$NETWORK" \
        | tail -1
}

ADMIN_ADDRESS="$(stellar keys address "$ADMIN")"

echo "==> Deploying dataset-registry"
REGISTRY=$(deploy "dataset_registry")
echo "    $REGISTRY"

echo "==> Deploying license-router"
LICENSE=$(deploy "license_router")
echo "    $LICENSE"

echo "==> Deploying quality-oracle"
ORACLE=$(deploy "quality_oracle")
echo "    $ORACLE"

echo "==> Deploying data-commission"
COMMISSION=$(deploy "data_commission")
echo "    $COMMISSION"

echo "==> Deploying royalty-splitter"
SPLITTER=$(deploy "royalty_splitter")
echo "    $SPLITTER"

echo "==> Initializing dataset-registry"
stellar contract invoke --id "$REGISTRY" --source "$ADMIN" --network "$NETWORK" \
    -- initialize --admin "$ADMIN_ADDRESS"

echo "==> Initializing license-router (registry: $REGISTRY)"
stellar contract invoke --id "$LICENSE" --source "$ADMIN" --network "$NETWORK" \
    -- initialize --admin "$ADMIN_ADDRESS" --registry_contract "$REGISTRY"

echo "==> Initializing quality-oracle"
stellar contract invoke --id "$ORACLE" --source "$ADMIN" --network "$NETWORK" \
    -- initialize --admin "$ADMIN_ADDRESS"

echo "==> Initializing data-commission"
stellar contract invoke --id "$COMMISSION" --source "$ADMIN" --network "$NETWORK" \
    -- initialize --admin "$ADMIN_ADDRESS"

echo "==> Initializing royalty-splitter"
stellar contract invoke --id "$SPLITTER" --source "$ADMIN" --network "$NETWORK" \
    -- initialize --admin "$ADMIN_ADDRESS"

echo "==> Wiring license-router -> quality-oracle"
stellar contract invoke --id "$LICENSE" --source "$ADMIN" --network "$NETWORK" \
    -- set_oracle --oracle_contract "$ORACLE"

echo "==> Wiring royalty-splitter -> quality-oracle"
stellar contract invoke --id "$SPLITTER" --source "$ADMIN" --network "$NETWORK" \
    -- set_oracle --oracle_contract "$ORACLE"

echo "==> Writing deployed addresses to $OUT_FILE"
cat > "$OUT_FILE" <<JSON
{
  "network": "$NETWORK",
  "dataset_registry": "$REGISTRY",
  "license_router": "$LICENSE",
  "royalty_splitter": "$SPLITTER",
  "quality_oracle": "$ORACLE",
  "data_commission": "$COMMISSION",
  "deployed_by": "$ADMIN_ADDRESS",
  "note": "Generated by deployment/deploy.sh — do not hand-edit; re-run the script to redeploy."
}
JSON

echo "==> Done. Deployed addresses written to $OUT_FILE"
